import:
  - ~/.config/alacritty/rose-pine.yml
env:
  TERM: xterm-256color
window:
  opacity: 0.9
  decorations_theme_variant: Dark
  startup_mode: Maximized
font:
  normal:
    family: Caskaydia Cove Nerd Font
    style: Regular
  bold:
    family: Caskaydia Cove Nerd Font
    style: Bold
  italic:
    family: Caskaydia Cove Nerd Font
    style: Italic